### ISSUE TITLE
Hello and Questions

### ISSUE THREAD

**Issue by DrkWithT** [BD103/BD103#7]
Hello! I just found your GitHub through the `replit.com` Discord. Seeing your compiler project got my attention, as I like those in the Replit community who do more advanced projects. I have checked out the FAQ on your site, and I figured that I would message you here.

My brief **About Me** should introduce myself just enough. If you would like to chat more, feel free to add me on Discord. I may be busy in my semester though.

FAQ:
 - How did you get into programming, and by which means do you learn programming concepts?
 - What project ideas would you recommend me to try implementing, in your opinion?
 - If you use Linux on a local computer, which distro do you like? (I like Mint overall since it looks familiar like Windows.)
 - Have you checked out _CSharpIsGud_ on `replit.com`? (If not, I recommend looking at them, as they have made interpreters and compilers too!)
 - What food dish do you like most?

That is all for now, enjoy your day (or night).

**Comment by BD103** [comment]
Hi there! I'm glad you are interested in my programming language. Here are some answers to your questions:

- I originally got into programming when I was 9. I first learned Scratch, but then decided to learn Python at 11. This was when I first started interacting with the Replit community. Recently (the past 6+ months?) I moved on the Rust. I liked how it was compiled and statically typed, but without the unsafely of C and superfluity of Java.
- Most programming concepts I learn through research online. I'm proud to say that I'm almost entirely self-taught. Usually I have a cool idea for a project, and then discover programming concepts related to that project along the way.
- For project ideas, it really depends on what you're looking for. A good project is a simple 2D video game, since it teaches good concepts on math, organization, and optimization. You could also try making utilities, which is what I enjoy doing. (Or you could help me with my programming language, if you're willing to learn Rust! :P)
- I've never used a full-blown Linux environment, though I do use both Windows and MacOS.
- I've seen CSharpIsGud in the Replit community, but I've never looked too deeply into their projects. I'll check them out after this!
- Hmmmm... that's a good question. The problem is that I don't have an answer! There are many good things out there, so it's too hard to decide.

I hope that provides a bit more information about myself!
